export const ui = {
  app: "relative flex h-full min-h-0 w-full flex-col overflow-hidden border border-[var(--foa-border)] bg-[var(--foa-panel)] text-[var(--foa-fg)]",
  appFloating: "rounded-none shadow-[-14px_0_48px_rgba(15,23,42,0.18)]",
  appEmbedded: "rounded-none shadow-[-10px_0_36px_rgba(15,23,42,0.1)]",
  header: "flex h-12 shrink-0 items-center gap-2.5 border-b border-[var(--foa-border)] py-0 pr-2.5 pl-2",
  iconButton: "grid h-[34px] w-[34px] cursor-pointer place-items-center rounded-[10px] border-0 bg-transparent text-[var(--foa-fg)] transition-[background,color,transform] duration-150 hover:bg-[var(--foa-soft)] active:translate-y-px",
  titleBlock: "flex min-w-0 flex-1 flex-col leading-[1.1]",
  title: "truncate text-[15px]",
  kicker: "text-[10px] font-bold tracking-[0.14em] text-[var(--foa-accent)] uppercase opacity-[0.85]",
  history: "absolute top-12 bottom-0 left-0 z-40 flex w-[78%] max-w-[260px] flex-col border-r border-[var(--foa-border)] bg-[var(--foa-panel)] shadow-[6px_0_28px_rgba(15,23,42,0.08)] transition-transform duration-200 ease-[cubic-bezier(0.22,1,0.36,1)]",
  historyHead: "flex items-center justify-between px-3 py-2.5 text-[11px] font-bold tracking-[0.1em] text-[var(--foa-muted)] uppercase",
  historyList: "flex-1 overflow-auto px-2 py-1.5",
  historyEmpty: "px-3 py-4 text-[13px] text-[var(--foa-muted)]",
  historyItem: "flex w-full cursor-pointer flex-col gap-0.5 rounded-[10px] border-0 bg-transparent px-2.5 py-2 text-left text-[var(--foa-fg)] hover:bg-[var(--foa-soft)]",
  historyTitle: "truncate",
  historyTime: "text-[var(--foa-muted)]",
  main: "min-h-0 flex-1",
  hero: "flex h-full flex-col justify-center overflow-auto px-5 py-6",
  heroEyebrow: "mb-2.5 inline-flex items-center gap-1.5 text-[10px] font-bold tracking-[0.14em] text-[var(--foa-accent)] uppercase",
  heroTitle: "m-0 mb-2 text-[30px] leading-[1.1] font-medium tracking-[-0.02em] max-sm:text-2xl",
  heroDescription: "m-0 mb-5 text-[15px] leading-[1.6] text-[var(--foa-muted)]",
  prompts: "flex flex-wrap gap-2",
  promptButton: "cursor-pointer rounded-full border border-[var(--foa-border)] bg-[rgba(255,255,255,0.55)] px-3 py-2 text-xs font-semibold text-[var(--foa-fg)]",
  messages: "h-full overflow-auto px-[18px] pt-4 pb-2",
  tools: "my-1.5 grid gap-[3px]",
  tool: "group overflow-hidden rounded-lg border-0 bg-transparent",
  inlineTool: "my-1",
  toolSummary: "flex cursor-pointer list-none items-center gap-2 border-b-0 py-1 text-sm leading-[1.6] font-bold text-[var(--foa-muted)] [&::-webkit-details-marker]:hidden",
  toolLabel: "inline-flex min-w-0 items-center gap-1.5",
  toolChevron: "shrink-0 text-[var(--foa-muted)]",
  toolTitle: "flex-1 truncate",
  toolPre: "ml-[13px] max-h-[220px] overflow-auto border-l-2 border-[var(--foa-border)] bg-[rgba(255,255,255,0.45)] px-2.5 py-2 font-mono text-[11px] leading-[1.45] whitespace-pre-wrap text-[var(--foa-muted)]",
  composer: "shrink-0 border-t border-[var(--foa-border)] bg-gradient-to-t from-[rgba(251,250,247,0.96)] to-[rgba(251,250,247,0.78)] px-3.5 pt-3 pb-3.5 max-sm:p-2.5",
  composerShell: "relative w-full rounded-[16px] border border-[var(--foa-border)] bg-[rgba(255,255,255,0.86)] pt-2.5 pr-2.5 pb-2 pl-[13px] shadow-[0_10px_32px_rgba(15,23,42,0.07)] transition-[border-color,box-shadow,background] duration-150 focus-within:border-[rgba(31,35,40,0.26)] focus-within:bg-[rgba(255,255,255,0.96)] focus-within:shadow-[0_0_0_3px_var(--foa-soft),0_14px_40px_rgba(15,23,42,0.1)] max-sm:rounded-[15px] max-sm:pt-[9px] max-sm:pr-[9px] max-sm:pb-2 max-sm:pl-3",
  textarea: "block max-h-[156px] min-h-[34px] w-full resize-none overflow-y-auto border-0 bg-transparent pt-1 pr-11 pb-1 pl-0.5 text-sm leading-[1.5] text-[var(--foa-fg)] outline-none placeholder:text-[var(--foa-muted)] placeholder:opacity-80",
  sendButton: "absolute right-2.5 bottom-2 inline-grid h-[34px] w-[34px] cursor-pointer place-items-center rounded-[10px] border border-transparent bg-[var(--foa-accent)] text-[var(--foa-accent-fg)] shadow-[0_8px_22px_rgba(15,23,42,0.16)] transition-[transform,box-shadow,opacity] duration-150 enabled:hover:-translate-y-px enabled:hover:shadow-[0_11px_26px_rgba(15,23,42,0.2)] enabled:active:translate-y-0 disabled:cursor-not-allowed disabled:opacity-40 disabled:shadow-none max-sm:right-[9px]",
};
